5  PRINT "INTRODUCE TWO NUMBERS:"
10 INPUT A
20 INPUT B
25 PRINT "THE NUMBERS INTRODUCED WHERE:"
30 PRINT A
40 PRINT B
45 PRINT "THE SUM IS:"
50 PRINT A+B
55 PRINT "THE SUBSTRACTION IS:"
60 PRINT A-B
65 PRINT "THE MULTIPLICATION IS:"
70 PRINT A*B
75 PRINT "THE DIVISION IS:"
80 PRINT A/B
90 END